// Command hashgen prints pre-computed API-name hash constants for use
// in shellcode-style API resolution.
//
// Usage:
//
//	go run ./cmd/hashgen -algo ror13 LoadLibraryA GetProcAddress
//	go run ./cmd/hashgen -algo fnv1a64 -package winsyms NtAllocateVirtualMemory NtCreateThreadEx
//	echo -e "LoadLibraryA\nGetProcAddress" | go run ./cmd/hashgen -algo djb2 -stdin
//
// Algorithms: ror13, ror13module, fnv1a32, fnv1a64, jenkins, djb2,
// crc32. See [github.com/oioio-space/maldev/hash] for the underlying
// implementations and reference vectors.
//
// Designed for `go generate` — emit a generated `.go` file once,
// commit it, ship without the runtime cost of re-hashing on every
// process start. The output uses the constant naming convention
// `Hash<AlgoSuffix><Symbol>` (e.g. `HashRor13LoadLibraryA`,
// `HashFnv1a64NtAllocateVirtualMemory`) to avoid collisions when
// multiple families coexist in the same package.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/oioio-space/maldev/hash"
)

func main() {
	var (
		algo    = flag.String("algo", "ror13", "hash algorithm: ror13, ror13module, fnv1a32, fnv1a64, jenkins, djb2, crc32")
		pkg     = flag.String("package", "", "package declaration to emit at the top of the output (omitted when blank)")
		stdin   = flag.Bool("stdin", false, "read symbol names line-by-line from stdin instead of args")
		out     = flag.String("o", "-", `output path (- for stdout)`)
		comment = flag.String("comment", "Code generated by hashgen; DO NOT EDIT.", "first-line comment")
	)
	flag.Parse()

	symbols, err := collectSymbols(*stdin, flag.Args())
	if err != nil {
		fmt.Fprintln(os.Stderr, "hashgen:", err)
		os.Exit(1)
	}

	emitter, suffix, bits, err := pickAlgo(*algo)
	if err != nil {
		fmt.Fprintln(os.Stderr, "hashgen:", err)
		os.Exit(2)
	}

	w, closer, err := openOutput(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "hashgen:", err)
		os.Exit(3)
	}
	defer closer()

	if *comment != "" {
		fmt.Fprintf(w, "// %s\n\n", *comment)
	}
	if *pkg != "" {
		fmt.Fprintf(w, "package %s\n\n", *pkg)
	}
	fmt.Fprintln(w, "const (")
	for _, s := range symbols {
		fmt.Fprintf(w, "\tHash%s%s = 0x%0*x\n", suffix, identifier(s), bits/4, emitter(s))
	}
	fmt.Fprintln(w, ")")
}

// collectSymbols pulls names either from positional args or from
// stdin (one per line, blank lines and # comments dropped).
func collectSymbols(useStdin bool, args []string) ([]string, error) {
	if useStdin {
		var names []string
		sc := bufio.NewScanner(os.Stdin)
		for sc.Scan() {
			line := strings.TrimSpace(sc.Text())
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			names = append(names, line)
		}
		if err := sc.Err(); err != nil {
			return nil, err
		}
		if len(names) == 0 {
			return nil, fmt.Errorf("stdin produced zero symbols")
		}
		return names, nil
	}
	if len(args) == 0 {
		return nil, fmt.Errorf("no symbol names supplied (pass as args or use -stdin)")
	}
	return args, nil
}

// pickAlgo returns the per-symbol hash callback boxed to a uint64,
// the camel-case suffix used in the const name, and the bit width
// (drives `%0*x` zero-padding so 32-bit hashes always emit 8 hex
// chars and 64-bit hashes 16).
func pickAlgo(name string) (func(string) uint64, string, int, error) {
	switch strings.ToLower(name) {
	case "ror13":
		return func(s string) uint64 { return uint64(hash.ROR13(s)) }, "Ror13", 32, nil
	case "ror13module":
		return func(s string) uint64 { return uint64(hash.ROR13Module(s)) }, "Ror13Module", 32, nil
	case "fnv1a32":
		return func(s string) uint64 { return uint64(hash.FNV1a32(s)) }, "Fnv1a32", 32, nil
	case "fnv1a64":
		return hash.FNV1a64, "Fnv1a64", 64, nil
	case "jenkins":
		return func(s string) uint64 { return uint64(hash.JenkinsOAAT(s)) }, "Jenkins", 32, nil
	case "djb2":
		return func(s string) uint64 { return uint64(hash.DJB2(s)) }, "Djb2", 32, nil
	case "crc32":
		return func(s string) uint64 { return uint64(hash.CRC32(s)) }, "Crc32", 32, nil
	}
	return nil, "", 0, fmt.Errorf("unknown algorithm %q", name)
}

func openOutput(path string) (io.Writer, func(), error) {
	if path == "-" {
		return os.Stdout, func() {}, nil
	}
	f, err := os.Create(path)
	if err != nil {
		return nil, nil, err
	}
	return f, func() { _ = f.Close() }, nil
}

// identifier sanitises a symbol name into a Go identifier suffix —
// strips characters Go won't accept in const names ("?", "@", "$",
// "."). The first character is uppercased so the resulting name is
// exported.
func identifier(s string) string {
	var b strings.Builder
	first := true
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z',
			r >= 'a' && r <= 'z',
			r >= '0' && r <= '9' && !first,
			r == '_':
			if first && r >= 'a' && r <= 'z' {
				r -= 'a' - 'A'
			}
			b.WriteRune(r)
			first = false
		}
	}
	return b.String()
}
