package sekurlsa

import (
	"bytes"
	"errors"
	"testing"

	"github.com/oioio-space/maldev/credentials/lsassdump"
)

// buildFixture produces a minidump in memory using the writer side of
// the credentials/lsassdump package so the round-trip test exercises
// real production format bytes (not a hand-rolled sketch). The
// returned blob carries the exact same on-wire layout an actual
// PROCESS_VM_READ-driven dump would.
func buildFixture(t *testing.T, modules []lsassdump.Module, regions []lsassdump.MemoryRegion) []byte {
	t.Helper()
	var buf bytes.Buffer
	cfg := lsassdump.Config{
		TimeDateStamp: 0x60000000,
		SystemInfo: lsassdump.SystemInfo{
			ProcessorArchitecture: 9, // AMD64
			NumberOfProcessors:    4,
			ProductType:           1, // Workstation
			MajorVersion:          10,
			MinorVersion:          0,
			BuildNumber:           19045, // Win10 22H2
			PlatformID:            2,     // NT
			CSDVersion:            "",
		},
		Modules: modules,
		Regions: regions,
	}
	if _, err := lsassdump.Build(&buf, cfg); err != nil {
		t.Fatalf("build fixture: %v", err)
	}
	return buf.Bytes()
}

// TestParse_NotMinidump verifies the signature gate fires when the
// caller hands us a random blob.
func TestParse_NotMinidump(t *testing.T) {
	blob := []byte("Not an MDMP at all, just text bytes that fill the header.....")
	_, err := Parse(bytes.NewReader(blob), int64(len(blob)))
	if !errors.Is(err, ErrNotMinidump) {
		t.Errorf("Parse non-MDMP err = %v, want ErrNotMinidump", err)
	}
}

// TestParse_TruncatedHeader covers the < headerLen short-circuit.
func TestParse_TruncatedHeader(t *testing.T) {
	_, err := Parse(bytes.NewReader([]byte("MDMP")), 4)
	if !errors.Is(err, ErrNotMinidump) {
		t.Errorf("truncated dump err = %v, want ErrNotMinidump", err)
	}
}

// TestParse_RoundTripBuildAndArch is the core Phase-1 contract: a
// dump generated by lsassdump.Build must parse back to the exact
// SystemInfo we wrote in. Without a registered template Parse
// returns ErrUnsupportedBuild + a partial Result that still carries
// detection-quality data (build, arch, modules).
func TestParse_RoundTripBuildAndArch(t *testing.T) {
	t.Cleanup(resetTemplates)
	resetTemplates()
	blob := buildFixture(t, nil, nil)
	res, err := Parse(bytes.NewReader(blob), int64(len(blob)))
	if !errors.Is(err, ErrUnsupportedBuild) {
		t.Fatalf("Parse no-template err = %v, want ErrUnsupportedBuild", err)
	}
	if res == nil {
		t.Fatal("Parse no-template res = nil; want partial Result")
	}
	if res.BuildNumber != 19045 {
		t.Errorf("BuildNumber = %d, want 19045", res.BuildNumber)
	}
	if res.Architecture != ArchX64 {
		t.Errorf("Architecture = %v, want ArchX64", res.Architecture)
	}
}

// TestReader_ParsesModuleNames asserts the ModuleList walker resolves
// every module's MINIDUMP_STRING into a Go string.
func TestReader_ParsesModuleNames(t *testing.T) {
	mods := []lsassdump.Module{
		{BaseOfImage: 0x7FF800000000, SizeOfImage: 0x100000, Name: "lsasrv.dll"},
		{BaseOfImage: 0x7FF801000000, SizeOfImage: 0x080000, Name: "msv1_0.dll"},
		{BaseOfImage: 0x7FF802000000, SizeOfImage: 0x0A0000, Name: "kerberos.dll"},
	}
	blob := buildFixture(t, mods, nil)

	r, err := openReader(bytes.NewReader(blob), int64(len(blob)))
	if err != nil {
		t.Fatalf("openReader: %v", err)
	}
	if got := len(r.modules); got != 3 {
		t.Fatalf("modules len = %d, want 3", got)
	}
	wantNames := []string{"lsasrv.dll", "msv1_0.dll", "kerberos.dll"}
	for i, m := range r.modules {
		if m.Name != wantNames[i] {
			t.Errorf("modules[%d].Name = %q, want %q", i, m.Name, wantNames[i])
		}
		if m.BaseOfImage != mods[i].BaseOfImage {
			t.Errorf("modules[%d].Base = 0x%X, want 0x%X", i, m.BaseOfImage, mods[i].BaseOfImage)
		}
	}
}

// TestReader_ReadVA_RoundTrip verifies that bytes injected into a
// MemoryRegion are recoverable via ReadVA at their captured kernel
// address. This is the core primitive every later phase relies on.
func TestReader_ReadVA_RoundTrip(t *testing.T) {
	const base = 0x7FF800100000
	payload := []byte{0xDE, 0xAD, 0xBE, 0xEF, 0x90, 0x90, 0x48, 0x33, 0xC0, 0xC3}
	blob := buildFixture(t, nil, []lsassdump.MemoryRegion{
		{BaseAddress: base, Data: payload},
	})

	r, err := openReader(bytes.NewReader(blob), int64(len(blob)))
	if err != nil {
		t.Fatalf("openReader: %v", err)
	}

	got, err := r.ReadVA(base, len(payload))
	if err != nil {
		t.Fatalf("ReadVA whole region: %v", err)
	}
	if !bytes.Equal(got, payload) {
		t.Errorf("whole region: got %X want %X", got, payload)
	}

	// Slice in the middle of the region — the descriptor offset must
	// be applied correctly so we don't get the wrong window.
	got, err = r.ReadVA(base+4, 4)
	if err != nil {
		t.Fatalf("ReadVA mid-region: %v", err)
	}
	if !bytes.Equal(got, payload[4:8]) {
		t.Errorf("mid region: got %X want %X", got, payload[4:8])
	}
}

// TestReader_ReadVA_AcrossRegions exercises the descriptor-spanning
// path: a single ReadVA covering the tail of region A and the head
// of region B (when their captured ranges abut).
func TestReader_ReadVA_AcrossRegions(t *testing.T) {
	const baseA = 0x7FF800200000
	const baseB = 0x7FF800200004 // immediately after A
	a := []byte{0xAA, 0xAA, 0xAA, 0xAA}
	b := []byte{0xBB, 0xBB, 0xBB, 0xBB}
	blob := buildFixture(t, nil, []lsassdump.MemoryRegion{
		{BaseAddress: baseA, Data: a},
		{BaseAddress: baseB, Data: b},
	})

	r, err := openReader(bytes.NewReader(blob), int64(len(blob)))
	if err != nil {
		t.Fatalf("openReader: %v", err)
	}

	got, err := r.ReadVA(baseA+2, 4)
	if err != nil {
		t.Fatalf("ReadVA across: %v", err)
	}
	want := []byte{0xAA, 0xAA, 0xBB, 0xBB}
	if !bytes.Equal(got, want) {
		t.Errorf("cross-region read: got %X want %X", got, want)
	}
}

// TestReader_ReadVA_NotInDump asserts a probe at an uncaptured kernel
// address surfaces an explicit error rather than silently returning
// zeros.
func TestReader_ReadVA_NotInDump(t *testing.T) {
	blob := buildFixture(t, nil, []lsassdump.MemoryRegion{
		{BaseAddress: 0x7FF800300000, Data: []byte{1, 2, 3, 4}},
	})

	r, err := openReader(bytes.NewReader(blob), int64(len(blob)))
	if err != nil {
		t.Fatalf("openReader: %v", err)
	}

	_, err = r.ReadVA(0x7FF800999000, 16) // unmapped
	if err == nil {
		t.Fatal("ReadVA missed range: want error, got nil")
	}
}

// TestArchitecture_String covers the enum's friendly-string mapping.
func TestArchitecture_String(t *testing.T) {
	cases := []struct {
		a    Architecture
		want string
	}{
		{ArchX64, "x64"},
		{ArchX86, "x86"},
		{ArchUnknown, "unknown"},
		{Architecture(99), "unknown"},
	}
	for _, c := range cases {
		if got := c.a.String(); got != c.want {
			t.Errorf("Architecture(%d).String() = %q, want %q", c.a, got, c.want)
		}
	}
}

// TestLogonType_String covers the LogonType enum's friendly-string
// mapping. Out-of-range values format with their integer for
// diagnostic transparency.
func TestLogonType_String(t *testing.T) {
	cases := []struct {
		lt   LogonType
		want string
	}{
		{LogonTypeInteractive, "Interactive"},
		{LogonTypeNetwork, "Network"},
		{LogonTypeRemoteInteractive, "RemoteInteractive"},
		{LogonTypeUnknown, "LogonType(0)"},
		{LogonType(42), "LogonType(42)"},
	}
	for _, c := range cases {
		if got := c.lt.String(); got != c.want {
			t.Errorf("LogonType(%d).String() = %q, want %q", c.lt, got, c.want)
		}
	}
}

// TestResult_Wipe is a smoke test that Wipe is safe to call on a nil
// receiver, an empty Result, and a Result whose credentials don't
// implement the optional wipe() interface.
func TestResult_Wipe(t *testing.T) {
	(*Result)(nil).Wipe() // must not panic
	r := &Result{}
	r.Wipe()
	r.Sessions = []LogonSession{{Credentials: []Credential{stubCred{}}}}
	r.Wipe() // stubCred has no wipe(); must not panic
}

type stubCred struct{}

func (stubCred) AuthPackage() string { return "stub" }

// TestParseFile_NotFound confirms ParseFile surfaces filesystem
// errors rather than masking them as parse errors.
func TestParseFile_NotFound(t *testing.T) {
	_, err := ParseFile("/nonexistent/path/no_such_dump.bin")
	if err == nil {
		t.Fatal("ParseFile on missing file: want error, got nil")
	}
}
