// Code generated by hand — DO NOT REGENERATE without checking ABI.
// CPUID instruction wrapper for amd64. Pure register move + CPUID +
// register move, no stack allocation. Caller frame already holds
// the return slots (Go ABI0).

#include "textflag.h"

// func cpuidRaw(leaf, subleaf uint32) (eax, ebx, ecx, edx uint32)
//
// Frame layout (24 bytes total):
//   offset 0:  leaf     uint32   (input)
//   offset 4:  subleaf  uint32   (input)
//   offset 8:  eax      uint32   (return)
//   offset 12: ebx      uint32   (return)
//   offset 16: ecx      uint32   (return)
//   offset 20: edx      uint32   (return)
TEXT ·cpuidRaw(SB), NOSPLIT, $0-24
	MOVL leaf+0(FP), AX
	MOVL subleaf+4(FP), CX
	CPUID
	MOVL AX, eax+8(FP)
	MOVL BX, ebx+12(FP)
	MOVL CX, ecx+16(FP)
	MOVL DX, edx+20(FP)
	RET
