// Code generated by hand — DO NOT REGENERATE without checking ABI.
// RDTSC + CPUID-bracketed-RDTSC primitives. RDTSC reads the CPU's
// 64-bit time-stamp counter into EDX:EAX. We compose EDX<<32 | EAX
// into a single uint64 for return.

#include "textflag.h"

// func rdtsc() uint64
//
// Plain RDTSC. NOT serialised — for the timing-attack variant use
// rdtscCpuidDelta which brackets a serialising CPUID.
TEXT ·rdtsc(SB), NOSPLIT, $0-8
	RDTSC
	SHLQ $32, DX
	ORQ  DX, AX
	MOVQ AX, ret+0(FP)
	RET

// func rdtscCpuidDelta() uint64
//
// Returns the cycle delta around a single serialising CPUID
// instruction. CPUID is forced as the timing target because it
// unconditionally VMEXITs under every modern hardware-assisted
// hypervisor (VMware, KVM, Xen, Hyper-V, VirtualBox HVM). The
// VMEXIT + VMM-side emulation + VMENTER round-trip adds 500-3000+
// cycles vs. a bare-metal CPUID's 30-50 cycle baseline.
//
// R8 holds the start TSC across the CPUID (which clobbers
// EAX/EBX/ECX/EDX). No stack slot needed — this is an ABI0 leaf
// with no callees.
TEXT ·rdtscCpuidDelta(SB), NOSPLIT, $0-8
	RDTSC
	SHLQ $32, DX
	ORQ  DX, AX
	MOVQ AX, R8

	// CPUID with EAX=0 is the smallest, most universally supported
	// leaf. Forces VMEXIT under HVM.
	XORL AX, AX
	CPUID

	RDTSC
	SHLQ $32, DX
	ORQ  DX, AX

	SUBQ R8, AX
	MOVQ AX, ret+0(FP)
	RET
