// Code generated by hand — DO NOT REGENERATE without checking ABI.
// SIDT / SGDT / SLDT instruction wrappers for amd64.
//
// Plan 9 amd64 assembler does not recognise SIDT/SGDT/SLDT as
// mnemonics, so each instruction is encoded as raw bytes:
//
//	SIDT (RDI): 0F 01 0F
//	SGDT (RDI): 0F 01 07
//	SLDT (RDI): 0F 00 07   ; 16-bit destination m16
//
// SIDT and SGDT store a 10-byte pseudo-descriptor in 64-bit mode
// (2-byte limit + 8-byte base). SLDT stores a 2-byte segment
// selector. The buffer pointer is passed via the `buf` slot in
// the Go ABI0 frame; the helpers do not allocate stack space.

#include "textflag.h"

// func sidtRaw(buf *byte)
// Writes 10 bytes (limit u16 + base u64) at *buf.
TEXT ·sidtRaw(SB), NOSPLIT, $0-8
	MOVQ buf+0(FP), DI
	BYTE $0x0F; BYTE $0x01; BYTE $0x0F
	RET

// func sgdtRaw(buf *byte)
// Writes 10 bytes (limit u16 + base u64) at *buf.
TEXT ·sgdtRaw(SB), NOSPLIT, $0-8
	MOVQ buf+0(FP), DI
	BYTE $0x0F; BYTE $0x01; BYTE $0x07
	RET

// func sldtRaw(buf *byte)
// Writes 2 bytes (segment selector) at *buf.
TEXT ·sldtRaw(SB), NOSPLIT, $0-8
	MOVQ buf+0(FP), DI
	BYTE $0x0F; BYTE $0x00; BYTE $0x07
	RET
