// Code generated by hand — DO NOT REGENERATE without checking ABI.
// VMware backdoor I/O port read for amd64.
//
// VMware exposes a backdoor at port 0x5658 ("VX"). When EAX is loaded
// with the magic 0x564D5868 ("VMXh") and an `IN EAX, DX` is issued
// against DX=0x5658, a VMware hypervisor traps the instruction and
// returns version data; on real hardware the I/O instruction faults
// (#GP at CPL 3 on modern OSes — IOPL is 0).
//
// Caller MUST be running with port-I/O privileges (CAP_SYS_RAWIO +
// iopl(3) on Linux; Ring 0 / Administrator + boot-time IOPM on
// Windows). The wrapper checks for this before invoking the asm.
//
// Plan 9 amd64 assembler does not recognise the IN/OUT mnemonics; the
// `IN EAX, DX` is encoded as the single byte 0xED.

#include "textflag.h"

// func vmwareBackdoorRaw(eaxIn, ecxIn uint32, regs *[4]uint32)
// Sets EAX = eaxIn, ECX = ecxIn, EDX = 0x5658, EBX = magic, then
// executes `IN EAX, DX`. Stores [EAX, EBX, ECX, EDX] (post-IN) into
// regs[0..4] for the Go caller to inspect.
//
// On a real (non-virtualised) machine this triggers SIGSEGV at the
// IN instruction. The wrapper catches that via the Go runtime's
// signal-handling fallback or by gating on a privilege check.
TEXT ·vmwareBackdoorRaw(SB), NOSPLIT, $0-24
	MOVL eaxIn+0(FP), AX
	MOVL ecxIn+4(FP), CX
	MOVQ regs+8(FP), DI

	MOVL $0x5658, DX            // VX port
	MOVL $0x564D5868, BX        // "VMXh" — second part of magic, used by some commands

	BYTE $0xED                  // IN EAX, DX

	MOVL AX, 0(DI)
	MOVL BX, 4(DI)
	MOVL CX, 8(DI)
	MOVL DX, 12(DI)
	RET
